# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kitnet_pb2 as kitnet__pb2


class KitNetStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessSample = channel.unary_unary(
                '/KitNet/ProcessSample',
                request_serializer=kitnet__pb2.ProcessSampleRequest.SerializeToString,
                response_deserializer=kitnet__pb2.ProcessSampleReply.FromString,
                )


class KitNetServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessSample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KitNetServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessSample': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessSample,
                    request_deserializer=kitnet__pb2.ProcessSampleRequest.FromString,
                    response_serializer=kitnet__pb2.ProcessSampleReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'KitNet', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KitNet(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessSample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KitNet/ProcessSample',
            kitnet__pb2.ProcessSampleRequest.SerializeToString,
            kitnet__pb2.ProcessSampleReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
