version: "3.2"
services:
    peregrine:
        build: .
        image: peregrine
        volumes:
            - type: bind
              source: ../../peregrine
              target: /home/docker/peregrine
            - type: bind
              source: ~/.gitconfig
              target: /home/docker/.gitconfig
              read_only: true
            - type: bind
              source: ~/.ssh
              target: /home/docker/.ssh
              read_only: true
            - ~/.Xauthority:/home/docker/.Xauthority
        environment:
            DISPLAY: $DISPLAY
        network_mode: "host"
        tty: true
        privileged: true
