version: "3.2"
services:
    peregrine-py:
        build: .
        image: peregrine-py
        volumes:
            - type: bind
              source: ../
              target: /home/docker/peregrine-py
            - type: bind
              source: /mnt/data/datasets
              target: /home/docker/datasets
            - type: bind
              source: ~/.gitconfig
              target: /home/docker/.gitconfig
              read_only: true
            - type: bind
              source: ~/.ssh
              target: /home/docker/.ssh
              read_only: true
            - type: bind
              source: ~/.vim
              target: /home/docker/.vim
              read_only: true
            - type: bind
              source: ~/.tmux
              target: /home/docker/.tmux
              read_only: true
            - ~/.Xauthority:/home/docker/.Xauthority
        environment:
            DISPLAY: $DISPLAY
        network_mode: "host"
        tty: true
        privileged: true
