# Pcap file path.
trace:
# Trace labels path.
labels:
# Current trace attack name.
attack:
# Execution phase sampling rate.
sampling:
# FM grace period.
fm_grace:
# AD grace period.
ad_grace:
# KitNET: m value.
max_ae:
# Ratio of exact stats in the overall training phase.
train_exact_ratio:
# Previously trained FM model path.
fm_model:
# Previously trained EL model path.
el_model:
# Previously trained OL model path.
ol_model:
# Previously trained stats struct path.
train_stats:
