# Pcap file path.
trace: /mnt/data/datasets/kitsune/active-wiretap/active-wiretap.pcap
# Trace labels path.
labels: /mnt/data/datasets/kitsune/active-wiretap/active-wiretap-labels.csv
# Current trace attack name.
attack: active-wiretap
# Execution phase sampling rate.
sampling: 64

hypr: [0.1, 0.1]
delta: [0.05, 0.05]
incr: True
release_speed: 1000
