# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kitnet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ckitnet.proto\"\xe4\x04\n\x14ProcessSampleRequest\x12\x0f\n\x07mac_src\x18\x01 \x01(\x04\x12\x0e\n\x06ip_src\x18\x02 \x01(\r\x12\x0e\n\x06ip_dst\x18\x03 \x01(\r\x12\x10\n\x08ip_proto\x18\x04 \x01(\r\x12\x10\n\x08port_src\x18\x05 \x01(\r\x12\x10\n\x08port_dst\x18\x06 \x01(\r\x12\r\n\x05\x64\x65\x63\x61y\x18\x07 \x01(\r\x12\x1a\n\x12mac_ip_src_pkt_cnt\x18\x08 \x01(\r\x12\x17\n\x0fmac_ip_src_mean\x18\t \x01(\r\x12\x1a\n\x12mac_ip_src_std_dev\x18\n \x01(\r\x12\x16\n\x0eip_src_pkt_cnt\x18\x0b \x01(\r\x12\x13\n\x0bip_src_mean\x18\x0c \x01(\r\x12\x16\n\x0eip_src_std_dev\x18\r \x01(\r\x12\x12\n\nip_pkt_cnt\x18\x0e \x01(\r\x12\x11\n\tip_mean_0\x18\x0f \x01(\r\x12\x14\n\x0cip_std_dev_0\x18\x10 \x01(\r\x12\x14\n\x0cip_magnitude\x18\x11 \x01(\r\x12\x11\n\tip_radius\x18\x12 \x01(\r\x12\x16\n\x0e\x66ive_t_pkt_cnt\x18\x13 \x01(\r\x12\x15\n\rfive_t_mean_0\x18\x14 \x01(\r\x12\x18\n\x10\x66ive_t_std_dev_0\x18\x15 \x01(\r\x12\x18\n\x10\x66ive_t_magnitude\x18\x16 \x01(\r\x12\x15\n\rfive_t_radius\x18\x17 \x01(\r\x12\x1b\n\x13ip_sum_res_prod_cov\x18\x18 \x01(\x04\x12\x0e\n\x06ip_pcc\x18\x19 \x01(\x04\x12\x1f\n\x17\x66ive_t_sum_res_prod_cov\x18\x1a \x01(\x04\x12\x12\n\nfive_t_pcc\x18\x1b \x01(\x04\"\"\n\x12ProcessSampleReply\x12\x0c\n\x04RMSE\x18\x01 \x01(\x02\x32G\n\x06KitNet\x12=\n\rProcessSample\x12\x15.ProcessSampleRequest\x1a\x13.ProcessSampleReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kitnet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROCESSSAMPLEREQUEST._serialized_start=17
  _PROCESSSAMPLEREQUEST._serialized_end=629
  _PROCESSSAMPLEREPLY._serialized_start=631
  _PROCESSSAMPLEREPLY._serialized_end=665
  _KITNET._serialized_start=667
  _KITNET._serialized_end=738
# @@protoc_insertion_point(module_scope)
